CREATE TABLE `interest_structure` (
  `id` int(11) NOT NULL,
  `name_en` varchar(100) DEFAULT NULL,
  `name_cn` varchar(100) DEFAULT NULL,
  `status` int(11) DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `id_UNIQUE` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (11,'Culture','文化艺术',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (12,'Jobs & Education','教育培训',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (13,'Games','游戏',0);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (14,'Consumer Electronics','消费数码',0);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (15,'Health & Wellness','健康医疗',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (16,'Beauty & Cosmetics','美容及化妆品',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (17,'Automobiles','汽车',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (18,'Sports & Fitness','运动健身',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (19,'Internet & Technology','IT及信息产业',0);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (20,'Baby & Maternity','母婴育儿',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (21,'Personal Finance','金融财经',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (22,'Consulting & Services','咨询及服务',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (23,'Industrial','工业',0);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (24,'Female Fashion','时尚',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (25,'Leisure Travel & Business Travel','旅游商旅',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (26,'Food & Drink','食品美食',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (27,'Home & Lifestyle','家居生活',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (29,'Office Equipment','电脑办公',0);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (30,'Alcohol','酒类',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (31,'Arts & Entertainment','娱乐',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (32,'Commerce','商业',0);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (33,'Festival','节日',0);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (1101,'Online Literature','网络小说',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (1102,'Culture/Literature','文化文学',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (1103,'Books/Magazines','书刊杂志',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (1104,'Humanities & Arts','人文艺术',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (1201,'Primary & Secondary Schooling','初级中级教育',0);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (1202,'Overseas Education','留学移民',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (1203,'MBA/EMBA','MBA/EMBA',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (1204,'Vocational & Continuing Education','职业技能培训',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (1205,'Early Childhood Education','早教幼教',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (1206,'Language Education','语言培训',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (1207,'University','大学',0);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (1208,'Private School','私立学校',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (1301,'Massive Multiplayer','大型客户端游戏',0);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (1302,'Online Games','网页游戏',0);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (1303,'Mobile Phone/Tablet Games','手机平板游戏',0);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (1304,'Mini Games & Flash Games','小游戏Flash游戏',0);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (1305,'Sports Games','电子竞技',0);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (1306,'Games Related Products','游戏周边',0);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (1401,'Mobile Phones/ Tablets','手机平板',0);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (1402,'Mobile Accessories','手机配件',0);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (1403,'Mobile Carrier','运营商',0);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (1404,'Desktops / Notebooks','台式机',0);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (1405,'Computer Hardware','电脑硬件',0);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (1406,'Digital Accessories','数码配件',0);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (1407,'Photography','摄影摄像',0);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (1408,'Fashional Videos','时尚影音',0);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (1409,'Smart Devices','智能设备',0);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (1410,'E-education','电子教育',0);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (1411,'Game Consoles','游戏机',0);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (1501,'Psychology','情感心理',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (1502,'Cosmetic Procedures','整形整容',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (1503,'Healthcare','保健养生',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (1504,'Sexual Health','两性健康',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (1601,'Skin Care','护肤',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (1602,'Daily Personal Care','洗护日用',0);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (1603,'Make-Up/Cosmetics','彩妆',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (1604,'Hair & Body','美发美体',0);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (1701,'High-End Cars','高档汽车',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (1702,'Mid-End Cars','中档汽车',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (1703,'Entry-Level Cars','入门级汽车',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (1704,'Vehicle Maintenance','养车用车',0);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (1705,'Used Cars','二手车',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (1706,'Rental Cars','汽车租赁',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (1707,'Car Manufacturers','汽车制造商',0);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (1708,'Auto Insurance','汽车保险',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (1709,'Auto Accessories','汽车周边',0);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (1710,'Luxury Cars','豪华汽车',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (1711,'Car Manufacturer Country','生产国家',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (1712,'Car Type','车型',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (1801,'Fitness','健身',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (1802,'Outdoor Sports','户外',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (1803,'Sports Events','体育赛事',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (1901,'Telecommunications/Services','电信、通信服务',0);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (1902,'Software','软件',0);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (1903,'E-commerce','电子商务',0);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (2001,'Maternity & Parenting','母婴用品',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (2002,'Family Services','亲子服务',0);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (2101,'Insurance','保险',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (2102,'Investing','投资理财',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (2103,'Real Estate & Construction','房地产及建筑',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (2201,'Wedding Services','婚庆',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (2202,'Careers','招聘求职',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (2203,'Dating','相亲交友',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (2401,'Clothing','服装',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (2402,'Jewelry/Accessories','首饰饰品',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (2403,'Designers & Collections','奢侈品',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (2404,'Shoes & Bags','鞋包',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (2501,'Hotels & Accommodations','酒店',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (2502,'Travel Destination','旅游目的地',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (2503,'Leisure Travel','旅游',0);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (2504,'Air Travel','航空',0);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (2505,'Travel Agencies & Services','旅行社',0);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (2601,'Cooking & Recipes','烹饪和菜谱',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (2602,'Snacks','休闲食品',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (2603,'Restaurants','餐馆美食',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (2604,'Healthy Food','保健食品',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (2605,'Fresh Food','生鲜食品',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (2606,'Local Food','地方特产',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (2607,'Drinks','饮料',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (2701,'Furniture Decoration','家居家装',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (2702,'Domestic Appliance','家用电器',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (2703,'Pets','宠物',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (2901,'Computers and Related Products','电脑及外设',0);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (2902,'Office Supplies','办公文具',0);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (3001,'Chinese Liquor/White Spirits','白酒',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (3002,'Wine','葡萄酒',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (3003,'Imported Wine','洋酒',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (3004,'Beer','啤酒',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (3005,'Nutritious Wine','养生酒',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (3101,'Variety & Entertainment','娱乐综艺',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (3102,'Movies','院线电影',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (3103,'TV Dramas','网络影视剧',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (3104,'Comics & Animation','动画漫画',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (3105,'Classical Music & Jazz','高雅音乐',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (3106,'Pop Music','流行音乐',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (3107,'Audio Equipment','音响器材',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (3108,'Musical Instruments','乐器',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (3301,'Christmas/New Year','圣诞节/元旦',0);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (3302,'Chinese New Year','春节',0);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (3303,'Lantern Festival','元宵节',0);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (3304,'Valentine\'s Day','情人节',0);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (3305,'Tomb-Sweeping Day','清明节',0);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (3306,'Easter','复活节',0);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (3307,'Dragon Boat Festival','端午节',0);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (3308,'Labor Day','劳动节',0);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (3309,'Mid-Autumn Festival','中秋节',0);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (3310,'Double Ninth Festival','重阳节',0);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (3311,'National Day','国庆节',0);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (3312,'Halloween','万圣节',0);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (3313,'Thanksgiving','感恩节',0);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (9901,'Automotive News','汽车资讯',0);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (9902,'Women\'s Fashion','女性时尚',0);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (9903,'Maternity & Babies','母婴育儿',0);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (9904,'Finance','金融财经',0);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (9905,'Travel','旅游酒店',0);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (9906,'Food & Beverage','美食吃货',0);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (9907,'Dating & Social','婚恋交友',0);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (9908,'Reading and Education','读书教育',0);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (9909,'Online Games','游戏对战',0);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (9910,'E-commerce','电子商务',0);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (9911,'Sports & Fitness','运动健身',0);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (9912,'Video Entertainment','视频娱乐',0);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (9913,'Men\'s Fashion','男性时尚',0);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (120201,'Foreign Language Exam','留学考试',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (120202,'Overseas Education Application','留学申请',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (120203,'Overseas Education Destination','留学移民国家',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (120801,'Private Kindergarten','私立幼儿园',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (120802,'Private Primary School','私立小学',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (120803,'Primary Middle & High School','私立中学',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (160101,'Anti-anging / Wrinkles','抗衰老去皱',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (160102,'Hydration','补水保湿',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (160103,'Brightening & Whitening','美白提亮祛斑',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (160104,'Sunscreen','隔离防晒',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (160105,'Cleansing & Makeup Removal','清洁卸妆',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (160106,'Men\'s Skincare','男士护肤',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (160107,'Acne Removing','祛痘',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (160108,'Anti-allergy','抗过敏',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (160109,'Eyecare','眼部护理',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (160110,'Bodycare','身体护肤',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (160301,'Face Makeup','面部彩妆',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (160302,'Eye Makeup','眼部彩妆',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (160303,'Lip Color','唇部彩妆',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (160304,'Nail Color & Handcare','指甲/手部',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (160305,'Makeup Tools','美发护发',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (171101,'Japan & Korea (Car)','日本韩国车',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (171102,'Germany (Car)','德国车',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (171103,'United States (Car)','美国车',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (171104,'China (Car)','国产车',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (171201,'Sedan','三厢车',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (171202,'Coupe','轿跑车',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (171203,'Hatchback','两厢车',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (171204,'SUV','越野车',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (171205,'Station Wagon','旅行车',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (171206,'Van','面包车',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (171207,'Convertible','敞篷车',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (171208,'MPV','多功能车',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (171209,'Sports Car','跑车',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (200101,'Diaper','婴幼儿尿裤',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (200102,'Baby Feeding','喂养用品',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (200103,'Baby Formula','婴幼奶粉',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (200104,'Baby Food','幼儿食品',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (200105,'Mother\'s Goods','妈妈用品',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (200106,'Baby Care','婴幼护理',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (200107,'Carriers & Strollers','童车推车',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (200108,'Car Seats','汽车安全座椅',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (200109,'Baby Bedding','婴儿寝具',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (210101,'Life Insurance','人寿保险',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (210102,'Health & Medical Insurance','健康保险',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (210103,'Property Insurance','财产保险',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (210201,'Personal Loan & Mortgage','个人贷款',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (210202,'Asset Management','投资和资产管理',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (210203,'Credit Card','信用卡',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (210204,'Retail Banking','银行零售服务',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (210301,'Property Development','开发商',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (210302,'Real Estate Agencies','中介代理',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (210303,'Property Management','物业管理',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (210304,'Real Estate','楼盘',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (250101,'Luxury Hotel','奢华酒店',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (250102,'High-end Hotel','高级酒店',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (250103,'Business Hotel','商务酒店',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (250104,'Economy Hotel','经济型酒店',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (250105,'Vacation Rental','度假型出租',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (250201,'North America (Travel)','北美旅游',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (250202,'SEA (Travel)','东南亚旅游',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (250203,'Japan / Korea (Travel)','日本 / 韩国旅游',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (250204,'Europe (Travel)','欧洲旅游',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (250205,'Africa (Travel)','非洲旅游',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (250206,'Australia & New Zealand (Travel)','大洋洲旅游 （澳洲 & 新西兰）',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (250207,'Hong Kong,Macau and Singapore (Travel)','港澳游',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (300101,'High-End Spirits','高档白酒',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (300102,'Mid-End Spirits','中档白酒',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (300103,'Low-End Spirits','低档白酒',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (300201,'White Wine','白葡萄酒',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (300202,'Red Wine','红葡萄酒',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (300203,'Rosé Wine','桃红葡萄酒',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (300204,'Sparkling Wine','起泡酒',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (300205,'Champagne','香槟',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (300206,'Sweet Wine/ Dessert Wine','甜酒 / 餐后酒',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (300207,'Country of Origin','产地',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (300301,'Whiskey','威士忌',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (300302,'Brandy','白兰地',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (300303,'Vodka','伏特加',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (300304,'Cocktail','鸡尾酒',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (300305,'Rum','朗姆酒',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (300306,'Tequila','龙舌兰',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (300307,'Gin','杜松子酒',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (300401,'Stout','黑啤',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (300402,'Yellow Beer','黄啤',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (300403,'White Beer','白啤',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (300404,'Fruit Beer','果啤',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (300501,'Yellow Rice Wine','黄酒',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (300502,'Tonic','滋补酒',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (300503,'Kumiss','奶酒',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (300504,'Sake','清酒',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (300505,'Shochu','烧酒',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (300506,'Plum','梅酒',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (300507,'Fruit Wine','果酒',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (12020301,'Europe (Education)','留学移民欧洲',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (12020302,'North America (Education)','留学移民北美',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (12020303,'Australia & New Zealand (Education)','留学移民澳洲',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (12020304,'Japan & Korea (Education)','留学移民日韩',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (12020305,'Hong Kong,Macau and Singapore (Education)','留学移民港澳新',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (30020701,'France (Wine)','法国酒',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (30020702,'Italy (Wine)','意大利酒',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (30020703,'Spain / Portugal (Wine)','西班牙 / 葡萄牙酒',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (30020704,'USA (Wine)','美国酒',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (30020705,'Australia / New Zealand (Wine)','澳洲 / 新西兰酒',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (30020706,'UK (Wine)','英国酒',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (30020707,'SA (Wine)','南非酒',1);
INSERT INTO `interest_structure` (`id`,`name_en`,`name_cn`,`status`) VALUES (30020708,'Chile / Argentina (Wine)','智利 / 阿根廷酒',1);
